joint_trajectory_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    joints:
      - fer_joint1
      - fer_joint2
      - fer_joint3
      - fer_joint4
      - fer_joint5
      - fer_joint6
      - fer_joint7
    allow_nonzero_velocity_at_trajectory_end: true
    gains:
      fer_joint1: {p: 300., d: 0.5, i: 5.0, i_clamp: 10.0, ff_velocity_scale: 0.8}
      fer_joint2: {p: 200., d: 0.5, i: 5.0, i_clamp: 10.0, ff_velocity_scale: 0.8}
      fer_joint3: {p: 300., d: 0.5, i: 5.0, i_clamp: 10.0, ff_velocity_scale: 0.8}
      fer_joint4: {p: 300., d: 0.2, i: 5.0, i_clamp: 10.0, ff_velocity_scale: 0.8}
      fer_joint5: {p: 200., d: 0.2, i: 10.0, i_clamp: 20.0, ff_velocity_scale: 0.8}
      fer_joint6: {p: 200., d: 0.1, i: 10.0, i_clamp: 20.0, ff_velocity_scale: 0.8}
      fer_joint7: {p: 100., d: 0.1, i: 10.0, i_clamp: 20.0, ff_velocity_scale: 0.8}
